apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-forecast-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: retail-forecast
  template:
    metadata:
      labels:
        app: retail-forecast
    spec:
      containers:
      - name: retail-forecast
        image: ${ECR_REPO}:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
